RELATORIOS_MOVIMENTOS_FATURA_BUTTON = '#main-nav > div > ul > li:nth-child(6) > ul > li:nth-child(6) > ul > li:nth-child(3) > a'
PERIODO_INICIO = '#dt_ini'
PERIODO_FIM = '#dt_fim'
PESQUISAR_BUTTON = '#filtrar'
GERAR_EXEL_BUTTON = '#content-wrapper > div > div > div > div:nth-child(3) > div > div > div > div > div > form > button'
